### PR TITLE
Completed feature no.1 from issue #162

### PR DESCRIPTION
**Pull request by tarunkumark**
added right arrow key shortcut to auto-fill placeholder text into text-area.

### CODE REVIEW

**Comment by kgashok** [comment]
@tarunkumark, 
Congrats on your first PR to a very popular open source repo!

**Comment by tarunkumark** [comment]
thank you sir! Looking forward to contribute more

**Comment by kgashok** [comment]
@tarunkumark @Pavithratrdev , 
Missing comments in the source code - add them along with your next PR. Thanks,

**Comment by tarunkumark** [comment]
Yes sir, will do.

**Pull request merged**
