### PR TITLE
[#58] Add topic attribution to saythanks link.

### PR DESCRIPTION
**Pull request by csurfer**
@BlitzKraft : Here is my solution to the #58 feature request I raised. Please take a look. Also since we do not have any contribution guide, I am not sure of any tests that needs to be run.

### CODE REVIEW

**Comment by BlitzKraft** [comment]
@csurfer The change looks good to me. Did you run it, and does it work as expected? 

I'll add the contribution guide soon. I'll run it and check when I get the time.

**Comment by csurfer** [comment]
@BlitzKraft : No I haven't run it since I couldn't find a way to run and test the flask server locally. DEVELOPMENT.md file lists a lot of variables that are needed to run the actual server which aren't necessary for local testing.

If you can provide details on how I can run the server locally, I can test it and provide you with details.

**Comment by BlitzKraft** [comment]
I received ownership of this quite recently and I'm figuring that out myself. Once I am able to run it, I'll test this. And then add a full contribution guide.

**Comment by kgashok** [comment]
@csurfer , sorry for the late response. Better late than never! 

Have you given it a thought as to How do you want the "topic" displayed in the inbox?

**Comment by Pavithratrdev** [comment]
Sir, I will work on this

**Comment by kgashok** [comment]
The default for the topic "your project", ends up confusing the header statement.
 
image

I propose to change as follows: 
1. Revert the header to `"Send Thank You note to UserName!"`
2. When topic is to be mentioned, add "about" + "Topic"

**Pull request merged**
