### PR TITLE
Add simpleMDE as md editor in submit note

### LINKED ISSUE #183: The Editor should support a Markdown text entry
- And a Preview feature when markdown is being used. 
- The note can also have Github recognized emojis?

### PR DESCRIPTION
**Pull request by tushar5526**
Fixed #183 

Check (put an 'x' between the square brackets) everything which applies:

- [x] I have added the issue number for which this pull request is created.

@Pavithratrdev @kgashok , please let me know about this update.

### CODE REVIEW

**Comment by tushar5526** [comment]
Screenshot from 2022-11-11 02-24-12

**Comment by tushar5526** [comment]
Also configured
- spell check
- autosave
- autofocus for editors

**Comment by tushar5526** [comment]
## Raw markdown
Screenshot from 2022-11-11 02-29-26

## Preview
Screenshot from 2022-11-11 02-29-51

**Comment by kgashok** [comment]
The editor is not usable on the Mobile. Please check @tushar5526

**Comment by tushar5526** [comment]
Noted @kgashok, I reproduced the bug and will raise a PR for it.

**Comment by tushar5526** [comment]
@kgashok I have made a new PR that will fix this issue.

**Pull request merged**
