### PR TITLE
Resolve #39.

### LINKED ISSUE #39: Don't escape <br> tags in notification mail
`<br>` tags are escaped in the `text/html` section. Mails look like this:
```
Dear n1try <br>Thank you <br>can u provide me source code of youtube video. <br>my email is ???. <br>Thanks again

--John Doe
```
According source code looks like this:
```
<html><body>
<p>Dear n1try &lt;br&gt;Thank you &lt;br&gt;can u provide me source code of=
 youtube video. &lt;br&gt;my email is ???. &lt;br&=
gt;Thanks again</p>
<p>--John Doe</p>
<p>=3D=3D=3D=3D=3D=3D=3D=3D=3D</p>
<p>This note of thanks was brought to you by SayThanks.io.</p>
<p>A Kenneth Reitz (me@kennethreitz.org) project.</p>
```

Additionally, the `text/plain` version shouldn't contain HTML tags at all, but it does.

```
Dear n1try <br>Thank you <br>can u provide me source code of youtube video.=
 <br>my email is ???. <br>Thanks again

-- John Doe
```

### PR DESCRIPTION
**Pull request by muety**
Fixes #39

### CODE REVIEW

**Comment by BlitzKraft** [comment]
@ParthS007 - I took over maintaining this repo. The changes look good to me.

**Comment by n1try** [comment]
@kennethreitz @ParthS007 @BlitzKraft Could somebody please take a look at this PR?

**Comment by n1try** [comment]
Push

**Comment by muety** [comment]
Any news on this??

**Comment by kgashok** [comment]
> Any news on this??

@muety - Please check. This was folded into a recent update.

**Pull request merged**
